### ISSUE TITLE
inspection tool doesn't show last seen

### ISSUE THREAD

**Issue by rudde0** [WiIIiam278/HuskClaims#263]
hey, I was testing various things in huskclaims and I realised that I can't see last seen data of claim owners. I have [huskclaims.inspect.view_last_seen](https://prnt.sc/RJaWVQjoRU9E) permission.

**Comment by WiIIiam278** [comment]
Fixed in 7c34b7b6abc5d91c5773c03b6187c0815e9791e3

**Comment by rudde0** [comment]
I think bug still continues.

https://prnt.sc/C3YUDC1_0VL7 default group has view last seen permission and I still can't see lalabu's claim (even getLastSeen is available).

**Comment by WiIIiam278** [comment]
> I think bug still continues.
> 
> https://prnt.sc/C3YUDC1_0VL7 default group has view last seen permission and I still can't see lalabu's claim (even getLastSeen is available).

Should be resolved for sure now.
